description: >
  "Join two CSV files by email and salary column"

join:
  src:
  - simple.csv
  - simple-join.csv
  columns:
    - "email"
    - "salary"
  how: "inner"
data:
  dest: exported-join.csv