description: >
  "Create multiple aggregates for simple.csv and release the data"

aggregate:
- alias: avg_salary
  columns:
  - salary
  function: avg
- alias: avg_age
  columns:
  - age
  function: avg
data:
  dest: exported-adult.csv
  src: simple.csv
release:
  - url: https://github.com/n-dusan/exporter-data-example
    strategy: tag
  - url: https://github.com/n-dusan/exporter-data-example-2
    strategy: commit